### ISSUE TITLE
Server wasn't able to start properly. Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by nathanhannig** [sandiegojs/sdjs-speaker-app#46]
After `npm install` and `npm run develop` of server code, I receive the following error.

```[2021-01-06T21:21:39.498Z] debug ⛔️ Server wasn't able to start properly.
[2021-01-06T21:21:39.501Z] error TypeError: Cannot read property 'includes' of undefined
    at Object.isPrivateAttribute (C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\node_modules\strapi-utils\lib\content-types.js:95:34)
    at C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\type-definitions.js:49:24
    at apply (C:\My Projects\sdjs-speaker-app\server\node_modules\lodash\lodash.js:475:27)
    at wrapper (C:\My Projects\sdjs-speaker-app\server\node_modules\lodash\lodash.js:5059:16)
    at C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\type-definitions.js:175:28
    at Array.filter (<anonymous>)
    at buildAssocResolvers (C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\type-definitions.js:175:6)
    at buildCollectionType (C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\type-definitions.js:401:12)
    at C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\type-definitions.js:288:16
    at Array.map (<anonymous>)
    at buildModels (C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\type-definitions.js:277:17)    at buildModelsShadowCRUD (C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\schema-generator.js:133:8)
    at Object.generateSchema (C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\services\schema-generator.js:29:42)
    at Object.initialize (C:\My Projects\sdjs-speaker-app\server\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:81:9)  
    at C:\My Projects\sdjs-speaker-app\server\node_modules\strapi\lib\hooks\index.js:36:28
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sdjs-speaker-api@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sdjs-speaker-api@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\break\AppData\Roaming\npm-cache\_logs\2021-01-06T21_21_39_545Z-debug.log
```

**Comment by nathanhannig** [comment]
Issue is caused by `package.json` versioning dependency allowing future incompatiable versions to be installed. It was installing version 3.4.1 for me.

`"strapi-plugin-graphql": "^3.0.5",`

Should be changed to 

`"strapi-plugin-graphql": "3.0.5",`

**Comment by nathanhannig** [comment]
As a side note, I believe Strapi originally built my project wrong due to the above error. The admin panel would throw errors after login.

I had to manually run `npm run build` for it to rebuild the build folder correctly after the changes were made.
